language: php
os: linux
php:
- '7.3'
sudo: required
services:
- mysql
before_script:
- composer self-update
script:
- chmod -R 777 *
- "./vendor/bin/phpunit tests"
deploy:
  provider: heroku
  api_key:
    secure: djViqMHeg/ZVedLUJ38FZo3R9/aZ8oPMlz9vXFucLayUO6BfxIlObRF+l7PUh6k7y17+dOj5QH45YxIQ5vt54Jg5/LZDX7WKVFobKJZ8X9hHZy8mwYZR3AxxLcyuotHLnl9y3+DA6GhCzKrJNvDNYrUTiYGifDin3DBxp3xfdZ783coaPnTkplkaomA/Bxi/YkovZEsPJj+xSUHW8epQ7Zj7HonLLPAz8duBIEYtoYfTTwkN50pf41M/Hie5tOVb29J6Fw4qFefSOGPohl8h5TIC8q6Ki7bmSseV2zajb9r2kY5ArdSfm58PzGub6keNYATlog4/kMlPTjBK7/0RiBkI2g+vxFqcZwj5tmwyzN1NBhIuzSRumsZdhco2+jrWlE5kq+WJVC6RUa/WNSy3DwXF+1bpVWQZgnbJCvdNYv5mXGphMUxGi2dUWG/dp+HL2+aOIhU7vRVS0QF7mIyWOUYCQDO0DtzaLlGekR7uuZDU4FmHUQwKs3O6NfYrfi/q9JqjlEIGv5O+LMKVEEkSlH3XPVis6sybdVAjohuve76qeM/8sIcoPiNhRmJVaelr+5Q1szNOZOY9T6g22MdisKuoO6oLP3NZGnoGSUp0ngkT+RlxUBJS4m201U47vuvdffQM38IaIOpytAz9PNOwmeQeEnHJCOA7Sj43LS7OK1U=
