language: php
os: linux
php:
- '7.3'
sudo: required
services:
- mysql
before_script:
- composer self-update
script:
- chmod -R 777 *
- "./vendor/bin/phpunit tests"
deploy:
  provider: heroku
  api_key:
    secure: pIYOIwLlADQl2m+Ij+Z63CJRMACdzHxJYRK5v1pTV39QKD9+0AsvMbE7YkjSj6g275OV5vS8Jw2mf+Q8k75E6LuTlCD5apcMGwvhr49wwhaF42aEyTjk3poF4MAXFreXvKnt5BI6avRHMrAeReTO28STFD18nefQwa27+PH45ETB5t0gXx3b6YDjGAcFH66vd652FerJuxiDKCdTNBfYXykJI7Q46fQbUPBGjLSWcHTW15BBkVFtnDYLdRsSJTsTBjZw8b2BfbPOdimmrAz36Aa0lPWl8VX5TbOn21qGoRIjh+e5Xo8qzsTSdNGriBdeFkUqcp55uuWgHB2e7+jcQB6eZZp5yfCPkcbhpEc6vlaUXPtGqwnUujE9KDlNdtySvPgBlj9vot7N/mCtYCUV0QXIPuxy53YOobCkHJyi7CKDcrqH49BcFG0Dw0F9vIVXXogVdWpwbA759/nbzp88EByXoZ9EVrUr4NzVj/wuCwagr1z5bg8NkpIrXO4zRixmsLdfIM3ly+GvmqyqHjUwyPt+s61istnTXP/k/L1lIFYR/XQeuSjNLSzW7Zbbys16pzQImDjnJtUVj+k2bN42MDs+SVEPPIAkLf6+KwYt8XJ0u833LXydUm4feFU3d6Ib8TrHEjmMCYI3bsHUMnhqO5psyjurqiJBDInFeYq2pn0=
