language: php
os: linux
php:
- '7.3'
sudo: required
services:
- mysql
before_script:
- composer self-update
script:
- chmod -R 777 *
- "./vendor/bin/phpunit tests"
deploy:
  provider: heroku
  api_key:
    secure: a0230138-c16e-4f73-8324-d1955f823ff4
