language: php
os: linux
php:
- '7.3'
sudo: required
services:
- mysql
before_script:
- composer self-update
script:
- chmod -R 777 *
- "./vendor/bin/phpunit tests --stderr"
deploy:
  provider: heroku
  api_key:
    secure: tg1eaJd9hxrdwNOHZWOMCZEq1vc3P8vlg9GlJxZZG7geLcjPvrkF3L0vxbP9WKR5MvkYiem+Zqqm8dBfDGx2N9hwBHY+0DYLzZWFcESPGhRy6ViKbkP5psssVL637IBZpxCY1iIMz9MGl8VoPj0PXUoWoddIxu5CSvm5kXEARKDGzMnzSc+ePXAOIMRNb+LaLFDgT9qPgfuZBFk6KnRSx9M8SgllWTzVGn6ELkIk5RMCxcF4q2BfLPIKKIPLw1ur7J4u9IPiHpGkj22Lir8Lvmjur7gkgSrBU+uWOuZC0A7fyvx7Nw9ok8UrO/k6XHQ7knR4MFdrQD+gczsTwG+H90n5kFPutRWl1cGLgczzrvwiQtXLj3suCWPGoy6V9fibgNHDJM6dueBvYSXB+G6ZHI6iiBeQbXtdyGmv/c4ttUkqfOk9Xwluf8Rb4m9C0jLGzRPQpOg1hcqBVye/ia2NwY/1WZ9nGhH1ZJnxoCpLWGYZmvvM/cR1FSh/4b9nbQ+3aHwNuaFbg5qbMUTCjEx/798WZjCPStLYwgdxrq5rAI8C7y19ER1gOZCOa7PFEOBDBwOL5OfWGb1wU+6AKKB1Mgw6d/ZPIHbFrMNM0ttbcJ8tpN6L4fhkPagljVuTqNjdab/v+kxmg2KzUUevVfSTaJxxubw6nTeKMA94z6MnspQ=
  app: barapates-heroku
