language: php
os: linux
php:
- '7.3'
sudo: required
services:
- mysql
before_script:
- composer self-update
script:
- chmod -R 777 *
- "./vendor/bin/phpunit tests"
deploy:
  provider: heroku
  api_key:
    secure: c0dxAhhT9LAZEkCk3af79P28CdYcCoRWOdrIDOx0Swge9TcCpTgaLoUNryc/bO2SfKohOzIkm5C5ZI+q6//ClbGl47ZsZhbjGJA0gqLnNAZLNyIKf+D91uQrChMzuDEzR1Jvk8ZDxlXhxTSnzoLcgync4L39XPgJm7tlX1K/4Ys+3pLzmbd4Vr59fzwZweXa8BRm1IFSRzcj26ECEv+b6V6yFTv5h5ZNtl2iInvSQzBfht79D6ns7mwbsDcp3D26WC/QskO4ltPxame6rn6J9IjLDyTR8E28I/jU935fi7piHXgr0p3yaBjUyRCwD1BXSQ9QxLTXle/4Cqt0m8o11q2gyejcoGK3E9t9+CQ83n0WefLbRfGK5+HMeDR92udUMw7tMkZZFVPb9B4SjH1EIX+bRRSEGeX543nSOXxioc94cwnHRyH72EY+n8DO5qAqZ/p4X+EUxRaph+IC7kETB9C4HizR4Muwym3fHMeTn3nNi0yXnRxcvoghKHta22hmpZHexof/IldHovej5ffYqnyfWKLrNiXLC8qfZNoDsmn0IHfn6xhOPWGdOFE5DstqicEZfwWXySSC+jdY8ptl/pgGAD60SQiD9wmXLqRoWK2HyFZAThQPmQ1ToNfTMpoePDKB2HZl+7PX8LA345p9RKFgo1UqBUekpFKLnfpUcGQ=
